### PR TITLE
Adds more functionality to the wvd file

### PR DESCRIPTION
**Pull request by Arias800**
This pull request adds the features that are detailed in this issue:  https://github.com/devine-dl/devine/issues/2
And did some cleanup too, because some lines were constantly repeat. So I centralized everything print in one function (except for dump which prints different information compared to the other functions).

### CODE REVIEW

**Comment by rlaphoenix** [comment]
Not sure I agree with the usage of that print function. I'd prefer without that. I also cannot accept the usage of `os` over `pathlib`.

**Comment by Arias800** [comment]
I'll change it tonight.

**Comment by Arias800** [comment]
It's done.
I have replaced every use of os module and remove the print function.

**Comment by rlaphoenix** [comment]
I haven't had the chance to look into this since. But I will look into this tomorrow or the day after.
In the mean time if you're able to resolve the conflicts made since a few updates, would be great.
If not, no biggie I will take a crack at it when I get the time.

I see why you made that print function, but the solution of throwing it into a random placed function with a broad name didn't float my boat. I will take a crack at it tomorrow, will see what I can dream up to resolve it. I'll most likely make some `WVD` class with a `__str__` representation or something. Will see.

**Comment by rlaphoenix** [comment]
I've rebased to fix the conflicts and squashed your 2x further commits.

**Comment by rlaphoenix** [comment]
Ok so, the github log is now spammed with force pushes over some squashes I made, but best believe every one of them counted towards the pull being better. I could have probably not pushed every squash change, but alas.

I think my variant here works out best. The main changes made is that I simply altered the UX of the functions. As in, you had code that would make it work for paths outside it, e.g., in delete, you could have it delete paths outside of the projects WVDs directory, which just isn't something that's necessary. Similarly you had code that converted a filename to a full path by using the WVDs directory as the parent directory. That's pointless since the goal is to put a file to that directory, so why would we want it to find an already added WVD, to just re-add it.

Also, you had it printing the WVD information as it added or deleted, which I feel is again unnecessary since `parse` exists to do that for you.

**Pull request merged**
